version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5433:5432"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5433
      DJANGO_DB_NAME: testdb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
